
[Other]
	#[NOT WORKING] This variable is responsible for enabling/disabling trades with villagers added by the mod
	enable_iafd_trades = true
	#This variable is responsible for give book on startup or not.
	give_book_on_startup = true

